name: DB Backup

on:
  workflow_dispatch:

env:
  host: ${{ secrets.HOST }}
  port: ${{ secrets.PORT }}
  db_user: ${{ secrets.DB_USER }}
  db_pass: ${{ secrets.DB_PASS }}
  db_name: ${{ secrets.DB_NAME }}
  zip_pass: ${{ secrets.ZIP_PASS }}
  dropbox_app_key: ${{ secrets.DROPBOX_APP_KEY }}
  dropbox_app_secret: ${{ secrets.DROPBOX_APP_SECRET }}
  dropbox_refresh_token: ${{ secrets.DROPBOX_REFRESH_TOKEN }}

jobs:
  db_backup:
    runs-on: ubuntu-latest
    name: Backup DB
    steps:
      - uses: actions/checkout@v4
      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Kolkata"
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mariadb-client
      - name: Run Shell Script
        id: shell_script_run
        run: bash ./db-backup.sh
