name: Scheduled DB Backup

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  db_backup:
    runs-on: ubuntu-latest
    name: Backup DB
    steps:
      - uses: actions/checkout@v4
      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Kolkata"
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mariadb-client zip
      - name: Run Shell Script
        id: shell_script_run
        run: bash ./db-backup.sh